### ISSUE TITLE
If you have an fdroid repo tool, then why not update your apps in fdroid?

### ISSUE THREAD

**Issue by herbsmn** [guardianproject/fdroid-repo-tools#1]
Your Orbot repo in F-Droid for example is 6 months old. Why isn't it updated?

**Comment by n8fr8** [comment]
We do not control f-droid.org. They build the apps, and someone else submitted the build recipes. We have our own self-hosted F-Droid repos, that you can enable within the F-Droid app (they are built in), or manually add here: https://guardianproject.info/fdroid

You can also subscribed to our nightly debug test builds here:
https://dev.guardianproject.info/debug

We do our best with our limited resources to keep all repositories of our apps up-to-date, but sometimes we don't. So it goes. You can ALWAYS find our latest APK files here: https://guardianproject.info/releases

**Comment by trilliums** [comment]
Is it documented somewhere how to subscribe to your nightly debug test builds? Also, I'd like to kindly suggest that you update F-droid with your most up to date apps. Keep up the great work that you do!

**Comment by eighthave** [comment]
we are working on getting all of our apps added to f-droid.org using a fully
reproducible build process.  That's not a small project, it takes time, and
contributions are welcome. So for now, the f-droid.org build recipes are
maintained by their original submitters while we are working towards having
our official releases be exactly the same as the releases included in f-droid.org
